name: mpv_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/KRTirtho/mpv_dart

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  eventify: ^1.0.0
  path: ^1.8.0
